### ISSUE TITLE
add bop's dependency declaration to mods.toml

### ISSUE THREAD

**Issue by zomb-676** [CartoonishVillain/MobCompack#18]
the mods.toml [file](https://github.com/CartoonishVillain/MobCompack/blob/1.18/src/main/resources/META-INF/mods.toml#L40-L65) only declares that MobCompack depends on Minecraft , forge and geckolib3

but this code source [file](https://github.com/CartoonishVillain/MobCompack/blob/1.18/src/main/java/com/cartoonishvillain/mobcompack/entity/Spawns.java) directly use bop's API without any checking like ModList.isModLoaded

please add the bop dependency declaration to make forge check this for you instead of just crashing

**Comment by CartoonishVillain** [comment]
fixed in MobCompack-0.0.3.4
